### ISSUE TITLE
有计划开发支持火狐的扩展吗 或者开一个播放分段flv视频的全浏览器支持项目

### ISSUE THREAD

**Issue by a1018148046** [nareix/mama-hd#11]

**Comment by nareix** [comment]
sorry，木有。。

**Comment by ivysrono** [comment]
Firefox 支持 MSE 毫无问题。安装
[hls.user.js](https://greasyfork.org/zh-CN/scripts/26981-hls-user-js)
就能支持 m3u8。
还是不能支持么？
