### ISSUE TITLE
不支持优酷的独播视频

### ISSUE THREAD

**Issue by l2dy** [nareix/mama-hd#3]
如 http://v.youku.com/v_show/id_XMTUyMjI5NDk1Ng==.html 。妈妈计划是支持的。

**Comment by l2dy** [comment]
![nanobar](https://cloud.githubusercontent.com/assets/14329097/14946528/e3459870-1012-11e6-812c-d6f6c768ee18.png)
原播放器变成“Flash”之后就没动静了。我是用packcrx.sh打包的。

**Comment by nareix** [comment]
用会员登录也还是一样吗？

**Comment by l2dy** [comment]
我没有会员。

**Comment by nareix** [comment]
@l2dy 貌似只有会员才能取到最高清晰度的 flv 源。mama2 方式不大一样，不是去取 flv。
