### ISSUE TITLE
B 站 interface.bilibili.com 失效

### ISSUE THREAD

**Issue by nareix** [nareix/mama-hd#6]
吗的现在获取不到视频了

**Comment by qfdk** [comment]
似乎是调用接口失效了。API调用失败.校验失败 求修复。

**Comment by nareix** [comment]
@qfdk 可否贴一下换好的那个 apikey，多谢了啊！我找到的都是和我用的一样。

**Comment by zythum** [comment]
坐等 appkey 😄😄😄😄😄

**Comment by nareix** [comment]
@zythum appkey=f3bb208b3d081dc8，从you-get找到，得救了！

**Comment by qfdk** [comment]
@nareix 果然咱们都是一样的 :) 
可以关注 bilidan 和 you-get 这两个项目来获得 key

**Comment by zythum** [comment]
@nareix 谢
