### ISSUE TITLE
部分视频不能完整播放

### ISSUE THREAD

**Issue by yemengsky** [nareix/mama-hd#7]
例如：http://v.youku.com/v_show/id_XMTY2MjA4MDkxNg==.html
播放到1分26秒就不会继续解码、播放

**Comment by yemengsky** [comment]
貌似是因为该视频气势是两段flv：
getVideosResult：
src
:
Array[2]
0
:
"http://124.14.11.117/youku/6775D69C7AF347409FC5D5D66/0300800200579A102B07AC2D9B7D2F96D03999-5276-239F-F919-D031393D4813.flv"
1
:
"http://124.14.12.4/youku/6574DD8257E3F74E9233B3ADE/0300800201579A102B07AC2D9B7D2F96D03999-5276-239F-F919-D031393D4813.flv"
length
:
2

**Comment by yemengsky** [comment]
第一段刚好1分27秒

**Comment by yemengsky** [comment]
哈哈，有点奇怪的是，我自己手动去下载的时候，第一段flv很快下好了，第二段很慢。感觉那应该不是插件的问题了。

**Comment by nareix** [comment]
是的，有的时候它下载很慢，会有这种情况
