### ISSUE TITLE
优酷不能播放了？

### ISSUE THREAD

**Issue by jediyoda36** [nareix/mama-hd#8]
有很多自媒体频道的视频看不了了、、

**Comment by nareix** [comment]
可以给个链接吗？

**Comment by jediyoda36** [comment]
http://v.youku.com/v_show/id_XMTcwMTExODU4NA==.html?beta&from=s1.8-1-1.2&spm=0.0.0.0.u4Tlat

**Comment by jediyoda36** [comment]
还有zealer频道下的也无法用

**Comment by nareix** [comment]
目测是 videoId 获取不到了，新的页面改变了 videoId 的位置。
