### ISSUE TITLE
Bilibili不能解析？

### ISSUE THREAD

**Issue by cnbeining** [nareix/mama-hd#9]
http://interface.bilibili.com/playurl?appkey=f3bb208b3d081dc8&cid=9812678

```
<?xml version="1.0" encoding="UTF-8"?>
<video>
	<code>-5003</code>
	<result>checksum error</result>
</video>
```

新解析参见

https://github.com/cnbeining/Biligrab/commit/ad91b72b5f37716534ce1870493712c7ce8f4a1b

我实在不想写JS（也不会），请酌情添加。thx.

**Comment by nareix** [comment]
fixed in https://github.com/nareix/mama-hd/commit/97263d45f26519ccd4bfe3d562a998163761f08a

多谢大神！Bilibili 最近好像各种改，然并卵！

**Comment by cnbeining** [comment]
然而我弄不出他HTML5播放器的解析。一个警钟。。

**Comment by nareix** [comment]
刚试了下，它 HTML5 的解析好像又不是这个规则了，B 站真是脑洞清奇。。

**Comment by cnbeining** [comment]
不一定。

他HTML5的手机API本来就不是这个。详情还是看我给的那个link。

新版测试HTML5的解析是按有APPKEY+APPSECRET解析的。而我取不到SECRET 这就很蛋疼了。

**Comment by nareix** [comment]
没事儿，只要大神搞出一个我们就够用了（
